### ISSUE TITLE
Introduce Taxonomy

### ISSUE THREAD

**Issue by alrik** [release-notes/release-notes#2]
As a developer i want to tag the modifications of a release to give them more context and to allow for filtering on them.

* [x] release-notes/release-notes-spec#4
* [x] release-notes/release-notes-schema#1
* [ ] release-notes/release-notes-cli#10

```yml
title: How Tagging may look like
description: >
  In order to give more context to a stated modification we could introduce
  some kind of optional changeset tagging.

releases:
  - version: Unreleased
    improved:
      - title: Adjust submit button color. 
        tags:
          - Android
          - UX
    fixed:
      - title: Fix some crash.
        tags:
          - iOS
    added:
      - Some fancy new feature. 
```
